name:                lsp-tester
version:             0.1.0.0
github:              "codedownio/lsp-tester"
license:             BSD3
author:              "Tom McLaughlin"
maintainer:          "tom@codedownio"
copyright:           "2022 Tom McLaughlin"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/lsp-tester#readme>

default-extensions:
- QuasiQuotes
- OverloadedStrings

dependencies:
- base >= 4.7 && < 5
- aeson
- aeson-qq
- data-default
- lsp-test
- string-interpolate

library:
  source-dirs: src

executables:
  lsp-tester-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lsp-tester

tests:
  lsp-tester-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lsp-tester
